# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "pry", "~> 0.11.3"

gem "rest-client", "~> 2.0"

gem "json", "~> 2.1"
