michelangelo = Human.create(name: 'Michelangelo', roast_preference: 'pizza', female: false)
leonardo = Human.create(name: 'Leonardo', roast_preference: 'pizza', female: false)
donatello = Human.create(name: 'Donatello', roast_preference: 'pepperoni', female: false)
raphael = Human.create(name: 'Raphael', roast_preference: 'dark', female: false)
april = Human.create(name: 'April', roast_preference: 'dark', female: true)

CoffeeCup.create(human: michelangelo, size: 3)
CoffeeCup.create(human: michelangelo, size: 20)
CoffeeCup.create(human: leonardo, size: 10000)
CoffeeCup.create(human: donatello, size: 89)
CoffeeCup.create(human: raphael, size: 72)
CoffeeCup.create(human: raphael, size: 437239587)
CoffeeCup.create(human: raphael, size: 1)
CoffeeCup.create(human: april, size: 8)